// Used with require.js setup

define([
    'jquery',
    'underscore',
    'backbone',
    'text!tpl/DisplayENOptionsView.html'
], function($, _, Backbone, ENOptionsTemplate) {

    var DisplayENOptionsView = Backbone.View.extend({


        initialize: function() {
            this.name = this.options.name;
            //this.options.vent.on("app:setupENPlaylistOptions", this.setup, this);
            this.render();
            //this.setup();

        },

        render: function() {
            var compiled_template = _.template(ENOptionsTemplate);
            $(this.el).html(compiled_template({uname: this.options.username}));
            //this.setup();
            return this;
        }


        /* Trying to do the jquery UI stuff here instead of in appinit (so we can keep track of child views generated by autocomplete) but doesn't seem to work
        setup: function() {
            var availableDescriptions = [
                'Rock',
                'Jazz',
                'Rap'
            ];
            //$('#slider').slider();
            $('#variety-slider').slider({
                min: 0,
                max: 1,
                step: 0.1,
                value: 0.5,
                slide: function(event, ui) {
                    $("#variety-level").html(ui.value);
                }
            });
            $('#description-autocomplete').autocomplete({
                source: availableDescriptions
            });
        }
        */


    });

    return DisplayENOptionsView;
});

